# Copyright (c) 2025 Gapry.
# Licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0).
# For details, see: https://creativecommons.org/licenses/by-nc-sa/4.0/
# See LICENSE file in the project root for full license information.

title: Gapry's Blog

email: gapry [at] protonmail [dot] com

description: ""

baseurl: "" 

url: "" 

twitter_username: ""

github_username:  ""

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  math_engine: mathjax

mathjax:
  src: https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-MML-AM_CHTML

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/gapry
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: https://twitter.com/_gapry
